### ISSUE TITLE
Extend Help

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/Instrument-Framework#105]
Currently ```HELP```
```json
{
  "jsonrpc": "2.0",
  "method": "HELP",
  "id": "cbecd84d7b67f502880067bacad1dfa8"
}
```
returns a list of support commands:

```json
{
  "jsonrpc": "2.0",
  "result": [
    "HELP",
    "ACK",
    "setConfiguration",
    "getAll",
    "getAllData",
    "Get Angle",
    "Get Helium Level",
    "Get Magnet",
    "Get Temperature",
    "Set Angle",
    "Set Chamber",
    "Set Magnet",
    "Set Temperature",
    "getAll"
  ],
  "id": "cbecd84d7b67f502880067bacad1dfa8"
}
```

Extend this so that HELP with the argument of of the commands will return the expected arguments and message format.

### Example:

```HELP Set Temperature```

```json
{
  "jsonrpc": "2.0",
  "method": "HELP",
  "params": {
    "Command": "Set Temperature"
  },
  "id": "cbecd84d7b67f502880067bacad1dfa8"
}
```

 should return:

```json
{
  "jsonrpc": "2.0",
  "results": {
    "jsonrpc": "2.0",
    "method": "Set Temperature",
    "params": {
      "Temperature (K)": 0,
      "Rate (K/min)": 0,
      "Channel": 0
    },
    "id": "#"
  },
  "id": "cbecd84d7b67f502880067bacad1dfa8"
}
```

**Comment by ciozi137** [comment]
Range of valid parameters would also be useful

**Comment by ciozi137** [comment]
```YAML
{
  "jsonrpc": "2.0",
  "method": "setTemperature",
  "params": {
    "temperature": 75,
    "_metadata": {
      "temperature": {
        "valid_range": [60, 90],
        "description": "Temperature must be between 60 and 90 degrees."
      }
    }
  },
  "id": 1
}
```
